[package]
name = "cody_flare_r"
version = "0.1.0"
authors = ["kb5000 <a123edcrfv@live.cn>"]
edition = "2018"

[dependencies]

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.7", features = ["winuser", "libloaderapi"]}
user32-sys = "0.2.0"
kernel32-sys = "0.2.2"
